### ISSUE TITLE
Required values

### ISSUE THREAD

**Issue by atreidesend** [willryan/factory.ts#15]
Hey, first off good to see a typescript factory library coming together.

Would be cool to have the option to define required props so that you can identify things that should always be provided (perhaps they have relationships to other records, foreign keys, etc). For example:
```typescript
interface Employee {
  id: number
  name: string
  managerId: number
}

// provide a list of 'required' keys as a type arg
const employeeFactory = Factory.Sync.makeFactory<Employee, 'managerId'>({
  id: Factory.each(i => i),
  name: 'Bob'
  // able to leave out required keys in the definition
})

// this would be typed to require providing `managerId`
const employee = employeeFactory.build({
  managerId: 3
})

// type errors
const employee = employeeFactory.build()
```

Thoughts?

**Comment by willryan** [comment]
@atreidesend: I think you can do this by saying the factory function will consume `Partial<T> & Pick<T,RequiredKeys>`  (or `Partial<Omit<T,RequiredKeys>> & Pick<T,RequiredKeys>`).  Though getting the signature to support the optional type parameter might be tricky.  Might be easier as a separate `makeFactoryWithRequired` function.

Want to take a crack at it?  Otherwise I'll try to get to it when I can.

**Comment by atreidesend** [comment]
@willryan yeah, good thoughts there, may also be a way to define it with some overload, I'll see if I can find some time this weekend to try it out and see what works

**Comment by jadengore** [comment]
It looks like this is [now supported](https://github.com/willryan/factory.ts#required-properties):
```ts
const employeeFactory = Factory.Sync.makeFactoryWithRequired<Employee, 'managerId'>({
  id: Factory.each(i => i),
  name: 'Bob'
})
```
Would you mind closing out this issue?
