### ISSUE TITLE
[Question] Can we nested the factory ?

### ISSUE THREAD

**Issue by wszgxa** [willryan/factory.ts#29]
Thanks for your contribution to this project. It's very helpfull.

So there is the question:

``` ts
interface Inner {
   innerString: string
}
interface Outer {
  innerObject: Inner
  OuterString: string
}
```

I need two factory one for Inner and another for Outer. Could we use the Inner factory inside outer? like this:

``` ts
const InnerFactory = Factory.Sync.makeFactory<Inner>({
  innerString: "mock string"
}}

const OuterFactory = Factory.Sync.makeFactory<Outer>({
  innerObject: InnerFactory.build()
  OuterString: "mock string"
})

```

Honestly, I don't like to nest it. But I can't find a reason why we should not do that.

Thanks.

**Comment by jannisg** [comment]
@wszgxa How did you solve this?

I have a similar issue where `IAccountInfo` has a nested interface of `IAccountAddress` so it's like (abbreviated):

```
interface IAccountAddress {
  street: string;
  zip: string;
  city: string;
}

interface IAccountInfo {
  firstName: string;
  lastName: string;
  address: IAccountAddress
}
```

I can't seem to generate the address fields inside the `address` object.

**Comment by jannisg** [comment]
Nevermind, finally got it working using:

```ts
const addressFactory = Factory.Sync.makeFactory({
  address: Factory.each(() => ({
    street: faker.address.streetAddress(),
    city: faker.address.city(),
    zip: faker.address.zipCode(),
  })),
});

export const accountInfoFactory: Factory.Sync.Factory<AccountInfo> = Factory.Sync.makeFactory(
  {
    id: Factory.each(i => i),
    name: Factory.each(() => faker.name.findName()),
  },
).combine(addressFactory);

```

For others that stumble upon this, what threw me off is that I tried to:
1. define the `const addressFactory` with `makeFactory<IAccountAddress>(...)` which obviously wasn't right due to the `address` key wrapping the actual fields
2. Instead of `const accountInfoFactory: Factory.Sync.Factory<AccountInfo> = Factory.Sync.makeFactory(...)` I had initially written `const accountInfoFactory = Factory.Sync.makeFactory<AccountInfo>(...)` which again, now that I look at it again mean that the `makeFactory` func was trying to validate the full `IAddressInfo` before the `.combine(...)` added the rest of the values.
