### ISSUE TITLE
Enhancement request: Nested partial?

### ISSUE THREAD

**Issue by dgreene1** [willryan/factory.ts#5]
Hi there. Is there a way to enhance the `.build` method such that you don't have to specify all of the  attributes of a nested override?

For instance, it would be nice to be able to override just budget without having to also have to specific name and typeOfFood as shown below:
```
interface IGroceryStore {
    aisle: {
       name: string;
       typeOfFood: string;
       budget: number;
    }
}

const groceryStoreFactory = factory.makeFactory<IGroceryStore>({
    aisle: {
       name: 'Junk Food Aisle',
       typeOfFood: 'Junk Food',
       budget: 3000
    }
})

const aStore = groceryStoreFactory.build({ // Error: Property 'name' is missing in type '{ budget: number; }
     aisle: {
         budget: 9999
     }
});
```

**Comment by willryan** [comment]
I think that's possible, but it may require some markup on the factory.  I.e.
```
const groceryStoreFactory = factory.makeFactory<IGroceryStore>({
    aisle: factory.nested({
       name: 'Junk Food Aisle',
       typeOfFood: 'Junk Food',
       budget: 3000
    })
})
```
Also, if you have an optional property in a type, but a factory declares a default real value (e.g. `123` for type `number?`), you will probably have to explicitly set it to `undefined` when you call build() if you want to switch to not having a value.

Anyway, I'm super busy for the next month, but I will put this on my list for early 2018.  I might have enough time to look at a pull request, though, if someone wants to jump in. ;)

**Comment by willryan** [comment]
I've taken a swing at this with [](https://github.com/willryan/factory.ts/tree/feature/nested-partials).  I'm mildly afraid I've broken other stuff, particularly on the compile time side of things (which is a bit harder to write a test for).  But please pull it down and see if it works for you.  I'm out of time to work on this today, but as soon as I can I'll do a bit more checking and then merge it in.

**Comment by mattvperry** [comment]
This has broken a different feature:

```ts
interface Entity {
  a: string,
  b?: string
}
const factory = Factory.makeFactory<Entity>({
  a: Factory.each(i => `Entity_${i}`)
});

var e = factory.build({ b: 'test' })

console.log(e.b) // this should be 'test' but is undefined because the new code is only overwriting keys that it can find and not adding new keys.
```

**Comment by willryan** [comment]
@mattvperry Thanks for the heads up.  I will try to have a fix out in the next few days.

**Comment by willryan** [comment]
@mattvperry should be fixed in 0.3.4.  Thanks for providing a breaking test. 😄

**Comment by mattvperry** [comment]
@willryan thank you for the quick turn around!

**Comment by G-Rath** [comment]
@willryan what ever happened to this? 

I've found this is pretty much a requirement for testing in TypeScript, and can't find any factory libraries for doing this.

Here's an example of the kind of types I'm working with (for a project using AwsLex):

```
interface LexIntent {
  name: string;
  slots: StringMap;
  slotDetails: Record<keyof LexIntent['slots'], SlotDetails>;
  confirmationStatus: 'Confirmed' | 'Denied' | 'None';
  sourceLexNLUIntentInterpretation: unknown;
}

export interface LexInputEvent {
  messageVersion: string;
  invocationSource: string;
  userId: string;
  sessionAttributes: object;
  requestAttributes: Nullable<Record<LexHeader, string>>;
  bot: LexBot;
  outputDialogMode: 'Text' | 'Voice';
  currentIntent: LexIntent;
  inputTranscript: string;
}
```

In Lex, `LexInputEvent#currentIntent#name` is a key property to figure out what logic to actually do - naturally in my unit tests usually only few of the properties (root-level or nested) are being tested at a time, so I'm wanting to be able to do something like:
```
Factory.makeLexInputEvent({ currentIntent: { name: 'greeting' } });
```

without TypeScript having a fit at me 😂

Understandably I don't expect this to be a 100% painless process, since this is in a manner going against the whole point of TypeScript, but I think it would be great to have a library that'd make this as easy as possible!

It seems that this issue fits with what I'm after, but as I said, I can't see any evidence on this issue that the feature was actually implemented, as the README doesn't mention anything close to nested types.
